var searchData=
[
  ['uint16flags_0',['Uint16Flags',['../classpython_1_1flatbuffers_1_1number__types_1_1Uint16Flags.html',1,'python::flatbuffers::number_types']]],
  ['uint32flags_1',['Uint32Flags',['../classpython_1_1flatbuffers_1_1number__types_1_1Uint32Flags.html',1,'python::flatbuffers::number_types']]],
  ['uint64flags_2',['Uint64Flags',['../classpython_1_1flatbuffers_1_1number__types_1_1Uint64Flags.html',1,'python::flatbuffers::number_types']]],
  ['uint8flags_3',['Uint8Flags',['../classpython_1_1flatbuffers_1_1number__types_1_1Uint8Flags.html',1,'python::flatbuffers::number_types']]],
  ['uintegerregex_4',['UIntegerRegex',['../classUIntegerRegex.html',1,'']]],
  ['unaryfunctor_5',['UnaryFunctor',['../structtesting_1_1gmock__more__actions__test_1_1UnaryFunctor.html',1,'testing::gmock_more_actions_test']]],
  ['unarymoveonlyfunctor_6',['UnaryMoveOnlyFunctor',['../structtesting_1_1gmock__more__actions__test_1_1UnaryMoveOnlyFunctor.html',1,'testing::gmock_more_actions_test']]],
  ['underlying_5fof_5fscalar_7',['underlying_of_scalar',['../structunderlying__of__scalar.html',1,'']]],
  ['underlying_5fof_5fscalar_3c_20t_2c_20true_20_3e_8',['underlying_of_scalar&lt; T, true &gt;',['../structunderlying__of__scalar_3_01T_00_01true_01_4.html',1,'']]],
  ['unioninnestedns_9',['unioninnestedns',['../classNamespaceA_1_1NamespaceB_1_1UnionInNestedNS.html',1,'NamespaceA.NamespaceB.UnionInNestedNS'],['../classNamespaceA_1_1NamespaceB_1_1UnionInNestedNS_1_1UnionInNestedNS.html',1,'NamespaceA.NamespaceB.UnionInNestedNS.UnionInNestedNS']]],
  ['unioninnestednstraits_10',['UnionInNestedNSTraits',['../structNamespaceA_1_1NamespaceB_1_1UnionInNestedNSTraits.html',1,'NamespaceA::NamespaceB']]],
  ['unioninnestednstraits_3c_20namespacea_3a_3anamespaceb_3a_3atableinnestedns_20_3e_11',['UnionInNestedNSTraits&lt; NamespaceA::NamespaceB::TableInNestedNS &gt;',['../structNamespaceA_1_1NamespaceB_1_1UnionInNestedNSTraits_3_01NamespaceA_1_1NamespaceB_1_1TableInNestedNS_01_4.html',1,'NamespaceA::NamespaceB']]],
  ['unioninnestednsunion_12',['UnionInNestedNSUnion',['../structNamespaceA_1_1NamespaceB_1_1UnionInNestedNSUnion.html',1,'NamespaceA::NamespaceB']]],
  ['unioninnestednsunion_5fjsonconverter_13',['UnionInNestedNSUnion_JsonConverter',['../classNamespaceA_1_1NamespaceB_1_1UnionInNestedNSUnion__JsonConverter.html',1,'NamespaceA::NamespaceB']]],
  ['unioninnestednsuniontraits_14',['UnionInNestedNSUnionTraits',['../structNamespaceA_1_1NamespaceB_1_1UnionInNestedNSUnionTraits.html',1,'NamespaceA::NamespaceB']]],
  ['unioninnestednsuniontraits_3c_20namespacea_3a_3anamespaceb_3a_3atableinnestednst_20_3e_15',['UnionInNestedNSUnionTraits&lt; NamespaceA::NamespaceB::TableInNestedNST &gt;',['../structNamespaceA_1_1NamespaceB_1_1UnionInNestedNSUnionTraits_3_01NamespaceA_1_1NamespaceB_1_1TableInNestedNST_01_4.html',1,'NamespaceA::NamespaceB']]],
  ['uniontraits_16',['uniontraits',['../structEvolution_1_1V1_1_1UnionTraits.html',1,'Evolution::V1::UnionTraits&lt; T &gt;'],['../structEvolution_1_1V2_1_1UnionTraits.html',1,'Evolution::V2::UnionTraits&lt; T &gt;']]],
  ['uniontraits_3c_20evolution_3a_3av1_3a_3atablea_20_3e_17',['UnionTraits&lt; Evolution::V1::TableA &gt;',['../structEvolution_1_1V1_1_1UnionTraits_3_01Evolution_1_1V1_1_1TableA_01_4.html',1,'Evolution::V1']]],
  ['uniontraits_3c_20evolution_3a_3av1_3a_3atableb_20_3e_18',['UnionTraits&lt; Evolution::V1::TableB &gt;',['../structEvolution_1_1V1_1_1UnionTraits_3_01Evolution_1_1V1_1_1TableB_01_4.html',1,'Evolution::V1']]],
  ['uniontraits_3c_20evolution_3a_3av2_3a_3atablea_20_3e_19',['UnionTraits&lt; Evolution::V2::TableA &gt;',['../structEvolution_1_1V2_1_1UnionTraits_3_01Evolution_1_1V2_1_1TableA_01_4.html',1,'Evolution::V2']]],
  ['uniontraits_3c_20evolution_3a_3av2_3a_3atableb_20_3e_20',['UnionTraits&lt; Evolution::V2::TableB &gt;',['../structEvolution_1_1V2_1_1UnionTraits_3_01Evolution_1_1V2_1_1TableB_01_4.html',1,'Evolution::V2']]],
  ['uniontraits_3c_20evolution_3a_3av2_3a_3atablec_20_3e_21',['UnionTraits&lt; Evolution::V2::TableC &gt;',['../structEvolution_1_1V2_1_1UnionTraits_3_01Evolution_1_1V2_1_1TableC_01_4.html',1,'Evolution::V2']]],
  ['unionvector_22',['UnionVector',['../classcom_1_1google_1_1flatbuffers_1_1UnionVector.html',1,'com::google::flatbuffers']]],
  ['unique_5fptr_23',['unique_ptr',['../classflatbuffers_1_1unique__ptr.html',1,'flatbuffers']]],
  ['unique_5fptr_3c_20std_3a_3astring_20_3e_24',['unique_ptr&lt; std::string &gt;',['../classflatbuffers_1_1unique__ptr.html',1,'flatbuffers']]],
  ['unittest_25',['UnitTest',['../classtesting_1_1UnitTest.html',1,'testing']]],
  ['unittesthelper_26',['UnitTestHelper',['../classtesting_1_1internal_1_1UnitTestHelper.html',1,'testing::internal']]],
  ['unittestimpl_27',['UnitTestImpl',['../classtesting_1_1internal_1_1UnitTestImpl.html',1,'testing::internal']]],
  ['unittestoptions_28',['UnitTestOptions',['../classtesting_1_1internal_1_1UnitTestOptions.html',1,'testing::internal']]],
  ['unittestrecordpropertytesthelper_29',['UnitTestRecordPropertyTestHelper',['../classtesting_1_1internal_1_1UnitTestRecordPropertyTestHelper.html',1,'testing::internal']]],
  ['universalprinter_30',['UniversalPrinter',['../classtesting_1_1internal_1_1UniversalPrinter.html',1,'testing::internal']]],
  ['universalprinter_3c_20const_20t_20_3e_31',['UniversalPrinter&lt; const T &gt;',['../classtesting_1_1internal_1_1UniversalPrinter_3_01const_01T_01_4.html',1,'testing::internal']]],
  ['universalprinter_3c_20t_20_26_20_3e_32',['UniversalPrinter&lt; T &amp; &gt;',['../classtesting_1_1internal_1_1UniversalPrinter_3_01T_01_6_01_4.html',1,'testing::internal']]],
  ['universalprinter_3c_20t_5bn_5d_3e_33',['UniversalPrinter&lt; T[N]&gt;',['../classtesting_1_1internal_1_1UniversalPrinter_3_01T_0fN_0e_4.html',1,'testing::internal']]],
  ['universalterseprinter_34',['UniversalTersePrinter',['../classtesting_1_1internal_1_1UniversalTersePrinter.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20char_20_2a_20_3e_35',['UniversalTersePrinter&lt; char * &gt;',['../classtesting_1_1internal_1_1UniversalTersePrinter_3_01char_01_5_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20char16_5ft_20_2a_20_3e_36',['UniversalTersePrinter&lt; char16_t * &gt;',['../classtesting_1_1internal_1_1UniversalTersePrinter_3_01char16__t_01_5_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20char32_5ft_20_2a_20_3e_37',['UniversalTersePrinter&lt; char32_t * &gt;',['../classtesting_1_1internal_1_1UniversalTersePrinter_3_01char32__t_01_5_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20const_20char_20_2a_20_3e_38',['UniversalTersePrinter&lt; const char * &gt;',['../classtesting_1_1internal_1_1UniversalTersePrinter_3_01const_01char_01_5_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20const_20char16_5ft_20_2a_20_3e_39',['UniversalTersePrinter&lt; const char16_t * &gt;',['../classtesting_1_1internal_1_1UniversalTersePrinter_3_01const_01char16__t_01_5_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20const_20char32_5ft_20_2a_20_3e_40',['UniversalTersePrinter&lt; const char32_t * &gt;',['../classtesting_1_1internal_1_1UniversalTersePrinter_3_01const_01char32__t_01_5_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20std_3a_3areference_5fwrapper_3c_20t_20_3e_20_3e_41',['UniversalTersePrinter&lt; std::reference_wrapper&lt; T &gt; &gt;',['../classtesting_1_1internal_1_1UniversalTersePrinter_3_01std_1_1reference__wrapper_3_01T_01_4_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20t_20_26_20_3e_42',['UniversalTersePrinter&lt; T &amp; &gt;',['../classtesting_1_1internal_1_1UniversalTersePrinter_3_01T_01_6_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20t_5bn_5d_3e_43',['UniversalTersePrinter&lt; T[N]&gt;',['../classtesting_1_1internal_1_1UniversalTersePrinter_3_01T_0fN_0e_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20wchar_5ft_20_2a_20_3e_44',['UniversalTersePrinter&lt; wchar_t * &gt;',['../classtesting_1_1internal_1_1UniversalTersePrinter_3_01wchar__t_01_5_01_4.html',1,'testing::internal']]],
  ['universe_45',['universe',['../structflatbuffers_1_1goldens_1_1Universe.html',1,'flatbuffers.goldens.Universe'],['../classpy_1_1flatbuffers_1_1goldens_1_1Universe_1_1Universe.html',1,'py.flatbuffers.goldens.Universe.Universe']]],
  ['universebuilder_46',['UniverseBuilder',['../structflatbuffers_1_1goldens_1_1UniverseBuilder.html',1,'flatbuffers::goldens']]],
  ['unprintableinfoo_47',['UnprintableInFoo',['../classfoo_1_1UnprintableInFoo.html',1,'foo']]],
  ['unprintabletemplateinglobal_48',['UnprintableTemplateInGlobal',['../classUnprintableTemplateInGlobal.html',1,'']]],
  ['unstreamable_49',['Unstreamable',['../classUnstreamable.html',1,'']]],
  ['unusedt_50',['UnusedT',['../classMyGame_1_1OtherNameSpace_1_1UnusedT.html',1,'MyGame::OtherNameSpace']]],
  ['uoffsettflags_51',['UOffsetTFlags',['../classpython_1_1flatbuffers_1_1number__types_1_1UOffsetTFlags.html',1,'python::flatbuffers::number_types']]],
  ['userconstructortag_52',['userconstructortag',['../structtesting_1_1internal_1_1DoAllAction_3_01FinalAction_01_4_1_1UserConstructorTag.html',1,'testing::internal::DoAllAction&lt; FinalAction &gt;::UserConstructorTag'],['../structtesting_1_1internal_1_1DoAllAction_3_01InitialAction_00_01OtherActions_8_8_8_01_4_1_1UserConstructorTag.html',1,'testing::internal::DoAllAction&lt; InitialAction, OtherActions... &gt;::UserConstructorTag']]],
  ['utf8_53',['Utf8',['../classcom_1_1google_1_1flatbuffers_1_1Utf8.html',1,'com::google::flatbuffers']]],
  ['utf8old_54',['Utf8Old',['../classcom_1_1google_1_1flatbuffers_1_1Utf8Old.html',1,'com::google::flatbuffers']]],
  ['utf8safe_55',['Utf8Safe',['../classcom_1_1google_1_1flatbuffers_1_1Utf8Safe.html',1,'com::google::flatbuffers']]],
  ['utiltest_56',['UtilTest',['../classtests_1_1py__flexbuffers__test_1_1UtilTest.html',1,'tests::py_flexbuffers_test']]]
];
